### ISSUE TITLE
使用实例方法绘制的虚线，在iOS上正常显示，在Android上显示为实线。

### ISSUE THREAD

**Issue by rzrobert** [xu-duqing/React-Native-ART-Sample#1]
createDashedView() {
    const path = new Path()
            .moveTo(1, 1)
            .lineTo(WINDOW_WIDTH, 1);
      return (
        <View style={{ backgroundColor: '#ffffff' }}>
          <Surface width={WINDOW_WIDTH} height={1}>
            <Shape d={path} stroke={CASHIER_GRAY_COLOR} strokeWidth={1} strokeDash={[1, 5]} />
          </Surface>
        </View>
      );
  }

**Comment by xu-duqing** [comment]
感兴趣可以看看原生的实现， 
https://github.com/facebook/react-native/blob/9ee815f6b52e0c2417c04e5a05e1e31df26daed2/ReactAndroid/src/main/java/com/facebook/react/views/art/ARTShapeShadowNode.java

`162： FLog.w(ReactConstants.TAG, "ART: Dashes are not supported yet!");`

Android 并不支持虚线的绘制

**Comment by rzrobert** [comment]
好的，谢谢。另外想请教一下，react-native-svg也不能在Android上绘制虚线是吗？

**Comment by xu-duqing** [comment]
不确定，如果仅仅是绘制虚线的话建议用拼图的方式。
