### ISSUE TITLE
ReactNativeJS: undefined is not an object (evaluating '_react.PropTypes.number')

### ISSUE THREAD

**Issue by kylema0421** [xu-duqing/React-Native-ART-Sample#14]
09-07 13:14:43.911  5239  5269 E ReactNativeJS: undefined is not an object (evaluating '_react.PropTypes.number')
09-07 13:14:43.930  5239  5269 E ReactNativeJS: Module AppRegistry is not a registered callable module (calling runApplication)

**Comment by xu-duqing** [comment]
@echo1994 问题没有说明清楚，猜测是你本身代码的问题和ART无关
