### ISSUE TITLE
question 请问下react native 如何绘制 orgchart 呢

### ISSUE THREAD

**Issue by zhmeng** [xu-duqing/React-Native-ART-Sample#16]
类似下面的图片，谢谢
![image](https://user-images.githubusercontent.com/5145566/34164925-d6454a9c-e515-11e7-9bcc-33599f1542df.png)

**Comment by xu-duqing** [comment]
@zhmeng 没有绘制过，不过计算好各个模块的坐标。挨个绘制应该不太复杂吧

**Comment by zhmeng** [comment]
嗯，是的。 我准备挨个绘制了。 谢谢。

**Comment by longunibbo** [comment]
How can you draw this orgchart? I'm looking for an instruction of this. I'd be grateful for if you can support me a bit. Thank you

**Comment by minhlucvan** [comment]
Hi @zhmeng, Can you please share the sample code on how to draw this chart, thanks
