### ISSUE TITLE
用什么IDE

### ISSUE THREAD

**Issue by setsuna** [xu-duqing/React-Native-ART-Sample#17]
右键点击项目 -> ‘Add Files to ProjectName -> 选择 node_modules/react-native/React/Libraries/ART/ART.xcodeproj’
android Studio 可以跑RN项目？

**Comment by xu-duqing** [comment]
如果是运行的话，执行去根目录执行 `npm install && npm run start-ios`  就可以了

**Comment by xu-duqing** [comment]
@setsuna 工程依赖已经升级，可以获取最新代码试一试。可以使用 `expo` 进行演示和调试，非常方便。

```
yarn & yarn start 
```
