### ISSUE TITLE
Android端wedge不能正常显示

### ISSUE THREAD

**Issue by GISerliang** [xu-duqing/React-Native-ART-Sample#8]
iOS端wedge圆弧正常显示，Android端wedge圆弧显示的是整个圆
![Uploading WX20170505-134541@2x.png…]()
![Uploading WX20170505-133944@2x.png…]()

**Comment by sillybill** [comment]
@GISerliang hello，I meet this problem today，it's so terrible！have you get this reason? or any way to fix it

**Comment by xu-duqing** [comment]
最新版本是已经支持了
